### ISSUE TITLE
Support for Apple silicon

### ISSUE THREAD

**Issue by victorbenichoux** [Cornerstone-OnDemand/modelkit#119]
`modelkit` does not seem to be installable on M1 macs with apple silicon.

It fails since the `numpy` version is pinned to 1.19.3 somehow, which cannot be installed on M1 macs.

**Comment by victorbenichoux** [comment]
Altogether, it feels like unless we require it through another dependency (e.g. TF), modelkit should not have `numpy` as a package requirement. This would solve the issue immediately, I will make a PR in that direction.

**Comment by victorbenichoux** [comment]
This is now fixed

**Comment by CyrilLeMat** [comment]
Great! Thanks Victor
