### ISSUE TITLE
click 8.1.0 breaks spaCy 3.2.3

### ISSUE THREAD

**Issue by mihaimm** [Cornerstone-OnDemand/modelkit#133]
Installing with 
`pip install modelkit spacy`
results in click 8.1.0 and spacy 3.2.3 being installed. But click 8.1.0 contains a breaking change and is incompatible with spaCy 3.2.3 (https://github.com/explosion/spaCy/issues/10564). 

Until updated spaCy is realeased, you need to install with 
`pyenv exec pip install modelkit spacy "click==8.0.4"`

**Comment by tgenin** [comment]
Maybe we want to specify a lower compatible spaCy version in the tutorial ?

**Comment by mihaimm** [comment]
I think this can be closed as spaCy 3.2.4 is out specifically for fixing incompatibility with click 8.1.0. So... now if we follow the tutorial it will work like described.

**Comment by CyrilLeMat** [comment]
great news @mihaimm . I'm closing the issue
