### ISSUE TITLE
[Feature request] Add profiler to modelkit model

### ISSUE THREAD

**Issue by llin17** [Cornerstone-OnDemand/modelkit#134]
I would like to propose a simple feature that can analyze resource consumption for model prediction. The usage is described as follows:

```python

model = modelkit.load_model(...)
profiler = Profiler(model) # Profiler could be customized
result = model(item)
profiler.summary() # output a DataFrame or str

# if there is no profiler, everything works as usual.
```

The output `profile.summary()` contains also the profiling result of each sub-models (defined in `self.model_dependencies` recursively). This requires only a few lines changes in `modelkit/core/model.py`.

**Comment by CyrilLeMat** [comment]
+1

**Comment by llin17** [comment]
The PR has been merged.
